"""add status for acceptor

Revision ID: 0754dad8ccb6
Revises: 62a33ce14acf
Create Date: 2024-12-08 19:01:16.833071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0754dad8ccb6'
down_revision = '62a33ce14acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor_check_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptor_level_1_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('acceptor_level_2_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('acceptor_level_3_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor_check_in', schema=None) as batch_op:
        batch_op.drop_column('acceptor_level_3_status')
        batch_op.drop_column('acceptor_level_2_status')
        batch_op.drop_column('acceptor_level_1_status')

    # ### end Alembic commands ###
