"""Initial database.

Revision ID: 23153163934a
Revises: 
Create Date: 2024-12-08 10:29:47.140952

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23153163934a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_image", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("second_level_password", sa.String(length=255), nullable=True),
        sa.Column("identity_card", sa.String(length=50), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("military_military_manager_id", sa.String(length=255), nullable=True),
        sa.Column("military_military_unit_id", sa.String(length=255), nullable=True),
        sa.Column("military_military_unit_name", sa.String(length=255), nullable=True),
        sa.Column(
            "military_military_manager_full_name", sa.String(length=255), nullable=True
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_manager", sa.Boolean(), nullable=False),
        sa.Column("left_image_path", sa.String(length=256), nullable=True),
        sa.Column("right_image_path", sa.String(length=256), nullable=True),
        sa.Column("front_image_path", sa.String(length=256), nullable=True),
        sa.Column("encoding_path", sa.String(length=256), nullable=True),
        sa.Column("role", sa.String(length=125), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_identity_card"), ["identity_card"], unique=True
        )

    op.create_table(
        "check_in",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("acceptor_level_1_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_1_full_name", sa.String(length=255), nullable=False),
        sa.Column("acceptor_level_2_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_2_full_name", sa.String(length=255), nullable=False),
        sa.Column("acceptor_level_3_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_3_full_name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("identity_card", sa.String(length=255), nullable=False),
        sa.Column(
            "military_military_manager_id", sa.String(length=255), nullable=False
        ),
        sa.Column(
            "military_military_manager_full_name", sa.String(length=255), nullable=False
        ),
        sa.Column("file_scan_path", sa.String(length=255), nullable=True),
        sa.Column("left_image_path", sa.String(length=255), nullable=True),
        sa.Column("right_image_path", sa.String(length=255), nullable=True),
        sa.Column("front_image_path", sa.String(length=255), nullable=True),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("accepted_datetime", sa.DateTime(), nullable=True),
        sa.Column("check_in_time", sa.DateTime(), nullable=True),
        sa.Column("check_out_time", sa.DateTime(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acceptor_level_1_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_2_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_3_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "military_units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent"],
            ["military_units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "relative_check_in",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("soldier_user_id", sa.Integer(), nullable=False),
        sa.Column("acceptor_level_1_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_1_full_name", sa.String(length=255), nullable=False),
        sa.Column("acceptor_level_2_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_2_full_name", sa.String(length=255), nullable=False),
        sa.Column("acceptor_level_3_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_3_full_name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("identity_card", sa.String(length=255), nullable=False),
        sa.Column("relationship", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("profile_image", sa.String(length=255), nullable=False),
        sa.Column("management_level", sa.String(length=255), nullable=False),
        sa.Column("unit_name", sa.String(length=255), nullable=False),
        sa.Column("file_scan_path", sa.String(length=255), nullable=True),
        sa.Column("left_image_path", sa.String(length=255), nullable=True),
        sa.Column("right_image_path", sa.String(length=255), nullable=True),
        sa.Column("front_image_path", sa.String(length=255), nullable=True),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("accepted_datetime", sa.DateTime(), nullable=True),
        sa.Column("check_in_time", sa.DateTime(), nullable=True),
        sa.Column("check_out_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("sponsor_id", sa.String(length=50), nullable=False),
        sa.Column("sponsor_identity_card", sa.String(length=50), nullable=False),
        sa.Column("sponsor_full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "sponsor_military_management_level", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "sponsor_military_military_unit", sa.String(length=255), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_1_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_2_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_3_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["soldier_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_identity_card"],
            ["users.identity_card"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "user_relatives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("identity_card", sa.String(length=50), nullable=False),
        sa.Column("relationship", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("profile_image", sa.String(length=255), nullable=False),
        sa.Column("sponsor_id", sa.String(length=50), nullable=False),
        sa.Column("sponsor_identity_card", sa.String(length=50), nullable=False),
        sa.Column("sponsor_full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "sponsor_military_management_level", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "sponsor_military_military_unit", sa.String(length=255), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_identity_card"],
            ["users.identity_card"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_relatives", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_relatives_identity_card"),
            ["identity_card"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_relatives", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_relatives_identity_card"))

    op.drop_table("user_relatives")
    op.drop_table("relative_check_in")
    op.drop_table("military_units")
    op.drop_table("check_in")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_identity_card"))

    op.drop_table("users")
    # ### end Alembic commands ###
