"""Initial database.

Revision ID: 36f96387413d
Revises: d09a069c7e63
Create Date: 2024-12-08 17:12:10.148760

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36f96387413d"
down_revision = "d09a069c7e63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("relative_check_in", schema=None) as batch_op:
        batch_op.alter_column(
            "soldier_user_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "unit_name", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("relative_check_in", schema=None) as batch_op:
        batch_op.alter_column(
            "unit_name", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "soldier_user_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
