"""update relative check identity card to allow None

Revision ID: 57af96f756fc
Revises: 69de815d06e0
Create Date: 2024-12-15 10:16:08.872754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57af96f756fc'
down_revision = '69de815d06e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relative_check_in', schema=None) as batch_op:
        batch_op.alter_column('identity_card',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relative_check_in', schema=None) as batch_op:
        batch_op.alter_column('identity_card',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
