"""add column

Revision ID: 62a33ce14acf
Revises: 96ef15d3c9c2
Create Date: 2024-12-08 18:44:44.660212

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62a33ce14acf"
down_revision = "96ef15d3c9c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sponsor_check_in", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("update_time", sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            "fk_user_created_by", "users", ["created_by_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sponsor_check_in", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_created_by", type_="foreignkey")
        batch_op.drop_column("update_time")
        batch_op.drop_column("created_by_id")

    # ### end Alembic commands ###
