"""Initial database.

Revision ID: 96ef15d3c9c2
Revises: 36f96387413d
Create Date: 2024-12-08 17:16:18.378134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ef15d3c9c2'
down_revision = '36f96387413d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relative_check_in', schema=None) as batch_op:
        batch_op.alter_column('acceptor_level_1_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('acceptor_level_2_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('acceptor_level_3_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sponsor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sponsor_identity_card',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('management_level')

    with op.batch_alter_table('sponsor_check_in', schema=None) as batch_op:
        batch_op.alter_column('acceptor_level_1_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('acceptor_level_2_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('acceptor_level_3_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('military_manager_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('military_manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('military_unit_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('is_manager',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_manager',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('sponsor_check_in', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('military_unit_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('military_manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('military_manager_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('acceptor_level_3_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('acceptor_level_2_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('acceptor_level_1_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('relative_check_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('management_level', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('sponsor_identity_card',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('sponsor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('acceptor_level_3_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('acceptor_level_2_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('acceptor_level_1_full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
