"""Initial database.

Revision ID: d09a069c7e63
Revises: 
Create Date: 2024-12-08 17:07:22.864221

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d09a069c7e63"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "military_units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent"],
            ["military_units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_image", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=500), nullable=True),
        sa.Column("second_level_password", sa.String(length=500), nullable=True),
        sa.Column("identity_card", sa.String(length=50), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("military_unit_name", sa.String(length=255), nullable=True),
        sa.Column("military_manager_full_name", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_manager", sa.Boolean(), nullable=False),
        sa.Column("military_unit_id", sa.Integer(), nullable=True),
        sa.Column("military_manager_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.Column("left_image_path", sa.String(length=256), nullable=True),
        sa.Column("right_image_path", sa.String(length=256), nullable=True),
        sa.Column("front_image_path", sa.String(length=256), nullable=True),
        sa.Column("encoding_path", sa.String(length=256), nullable=True),
        sa.Column("role", sa.String(length=125), nullable=False),
        sa.Column("reset_token", sa.String(length=256), nullable=True),
        sa.Column("reset_second_token", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name="fk_user_created_by"
        ),
        sa.ForeignKeyConstraint(
            ["military_manager_id"], ["users.id"], name="fk_user_military_manager"
        ),
        sa.ForeignKeyConstraint(
            ["military_unit_id"], ["military_units.id"], name="fk_user_military_unit"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_identity_card"), ["identity_card"], unique=True
        )

    op.create_table(
        "relative_check_in",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("soldier_user_id", sa.Integer(), nullable=False),
        sa.Column("acceptor_level_1_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_1_full_name", sa.String(length=255), nullable=False),
        sa.Column("acceptor_level_2_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_2_full_name", sa.String(length=255), nullable=False),
        sa.Column("acceptor_level_3_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_3_full_name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("identity_card", sa.String(length=255), nullable=False),
        sa.Column("relationship", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("profile_image", sa.String(length=255), nullable=False),
        sa.Column("management_level", sa.String(length=255), nullable=False),
        sa.Column("unit_name", sa.String(length=255), nullable=False),
        sa.Column("file_scan_path", sa.String(length=255), nullable=True),
        sa.Column("left_image_path", sa.String(length=255), nullable=True),
        sa.Column("right_image_path", sa.String(length=255), nullable=True),
        sa.Column("front_image_path", sa.String(length=255), nullable=True),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("accepted_datetime", sa.DateTime(), nullable=True),
        sa.Column("check_in_time", sa.DateTime(), nullable=True),
        sa.Column("check_out_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("sponsor_full_name", sa.String(length=255), nullable=True),
        sa.Column("sponsor_military_unit_name", sa.String(length=255), nullable=True),
        sa.Column(
            "sponsor_military_manager_full_name", sa.String(length=255), nullable=True
        ),
        sa.Column("sponsor_id", sa.Integer(), nullable=False),
        sa.Column("sponsor_identity_card", sa.String(length=50), nullable=False),
        sa.Column("sponsor_military_unit_id", sa.Integer(), nullable=True),
        sa.Column("sponsor_military_manager_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acceptor_level_1_id"],
            ["users.id"],
            name="fk_relative_check_in_acceptor_level_1_id",
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_2_id"],
            ["users.id"],
            name="fk_relative_check_in_acceptor_level_2_id",
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_3_id"],
            ["users.id"],
            name="fk_relative_check_in_acceptor_level_3_id",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_relative_check_in_created_by"
        ),
        sa.ForeignKeyConstraint(
            ["soldier_user_id"],
            ["users.id"],
            name="fk_relative_check_in_soldier_user_id",
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_id"], ["users.id"], name="fk_relative_check_in_sponsor_id"
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_identity_card"],
            ["users.identity_card"],
            name="fk_relative_check_in_sponsor_identity_card",
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_military_manager_id"],
            ["users.id"],
            name="fk_relative_check_in_sponsor_military_manager_id",
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_military_unit_id"],
            ["military_units.id"],
            name="fk_relative_check_in_sponsor_military_unit_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "sponsor_check_in",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("acceptor_level_1_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_1_full_name", sa.String(length=255), nullable=False),
        sa.Column("acceptor_level_2_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_2_full_name", sa.String(length=255), nullable=False),
        sa.Column("acceptor_level_3_id", sa.Integer(), nullable=True),
        sa.Column("acceptor_level_3_full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("identity_card", sa.String(length=255), nullable=False),
        sa.Column("military_manager_full_name", sa.String(length=255), nullable=False),
        sa.Column("military_manager_id", sa.Integer(), nullable=False),
        sa.Column("military_unit_name", sa.String(length=255), nullable=False),
        sa.Column("military_unit_id", sa.Integer(), nullable=True),
        sa.Column("file_scan_path", sa.String(length=255), nullable=True),
        sa.Column("left_image_path", sa.String(length=255), nullable=True),
        sa.Column("right_image_path", sa.String(length=255), nullable=True),
        sa.Column("front_image_path", sa.String(length=255), nullable=True),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("accepted_datetime", sa.DateTime(), nullable=True),
        sa.Column("check_in_time", sa.DateTime(), nullable=True),
        sa.Column("check_out_time", sa.DateTime(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["acceptor_level_1_id"],
            ["users.id"],
            name="fk_sponsor_check_in_acceptor_level_1_id",
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_2_id"],
            ["users.id"],
            name="fk_sponsor_check_in_acceptor_level_2_id",
        ),
        sa.ForeignKeyConstraint(
            ["acceptor_level_3_id"],
            ["users.id"],
            name="fk_sponsor_check_in_acceptor_level_3_id",
        ),
        sa.ForeignKeyConstraint(
            ["military_manager_id"],
            ["users.id"],
            name="fk_sponsor_check_in_military_manager_id",
        ),
        sa.ForeignKeyConstraint(
            ["military_unit_id"],
            ["military_units.id"],
            name="fk_sponsor_check_in_military_unit_id",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_sponsor_check_in_user_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sponsor_check_in")
    op.drop_table("relative_check_in")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_identity_card"))

    op.drop_table("users")
    op.drop_table("military_units")
    # ### end Alembic commands ###
