"""add check in and check out image

Revision ID: e5805ada6213
Revises: 57af96f756fc
Create Date: 2025-02-15 11:40:43.927980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5805ada6213'
down_revision = '57af96f756fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relative_check_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('check_out_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relative_check_in', schema=None) as batch_op:
        batch_op.drop_column('check_out_image')
        batch_op.drop_column('check_in_image')

    # ### end Alembic commands ###
